---
title: "HW2"
author: "Pei-Ju Chien"
date: "2023-03-01"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# 第一題
```{r}
market = read.csv("marketing_data.csv")
str(market) 
```

```{r}
install.packages('skim',repos = "http://cran.us.r-project.org")
library(skimr)
skim(market) 
```

# 第二題
```{r}
names(market)
```

# 第三題
```{r}
head(rowSums(is.na(market)))
```

# 第四題
```{r}
head(colSums(is.na(market)))
skim(market)
```

# 第五題
```{r}
install.packages('psych',repos = "http://cran.us.r-project.org")
library(psych)
psych::describe(market)
summary(market)

# 當遇到字元變數時，describe()提供單字出現的頻率跟比例。
```

# 第六題
```{r}
# table(market$Education,market$Marital_Status,market$Country)
table(market['Education'])
table(market['Marital_Status'])
table(market['Country'])
pairTable <- table(market$Education, market$Marital_Status)
pairTable

table(market$Education)
table(market$Marital_Status)
table(market$Country)
table(market$Education, market$Marital_Status) 

# table()會回傳一個列聯表，顯示兩個變量中每個水平組合的頻率計數。 生成的表格可用於探索兩個變數之間的關係並識別任何模式或趨勢。
```

# 第七題
```{r}
market['Income']
# 因為他前面有一個'$'的字元，所以不能算是 numeric variable。 
```

# 第八題
```{r}
install.packages('skim',repos = "http://cran.us.r-project.org")
library(skimr)
Nunique = apply(market,2,n_unique)
col = colnames(market)[Nunique == 2]
tbl = apply(market[,col],2,table)
ratio = apply(market[,col],2,mean)
Nunique
# apply()函數的第一個參數market是一個數據框，第二個參數2表示對column進行操作，第三個參數n_unique是對每一個column使用這個函數。因此，apply(market,2,n_unique)將對market數據框的每一column執行n_unique函數，返回一個向量，其中每個元素都是該列中唯一值的數量。

col
# 找Nunique中的值為2的變數。

tbl
# 回傳一個列表，其中的元素是 market 數據集中唯一值數量為 2 的變數（col）的分佈表，每個分佈表顯示了變數中每個唯一值出現的次數。

ratio
# 回傳一個向量，其中的值代表 market 數據集中唯一值數量為 2 的變數（欄位）中每個唯一值的平均數值。
```

# 第九題
```{r}
myf = function(var,byvar)
{
  by = unique(byvar)
  mout = NULL
  for (i in by) {
    s = subset(var,byvar == i)
    m = colMeans(s)
    mout = cbind(mout,m)
  }
  colnames(mout) = by
  mout
}

varlist = c("MntWines","MntSweetProducts",
            "MntMeatProducts","MntFishProducts",
            "MntGoldProds")
colspec = c(4,2,1,5,8)
tbl = myf(subset(market,,varlist),market$Education)

tbl
barplot(tbl, beside = T, col = colspec)
legend("topright", inset = c(0,0), legend = varlist, 
       col = colspec, pch = 16, cex = 1.1)
```

```{r}
agegrp = ifelse(market$Year_Birth < 1960,"<1960",
                ifelse(market$Year_Birth < 1970,"[1960,1970)",
                       ifelse(market$Year_Birth < 1980,"[1970,1980)",">=1980")))
#他利用”ifelse”把”market”中的” Year_Birth”分成四組。當”Year_Birth”小於”1960”就在第一組，如果”Year_Birth”沒有小於”1960”但小於”1970”，則落在第二組。如果”Year_Birth”沒有小於”1970”但小於”1980”則落在第三組。剩下的就是”Year_Birth”大於”1980”，會被分到第四組。
table(agegrp)
```

```{r}
varlist = c("Kidhome","Teenhome")
tbl = myf(subset(market,,varlist),agegrp)
tbl

# tbl存的是myf回傳的結果。myf有兩的input，一個是var，這邊給的例子是market中"MntWines","MntSweetProducts","MntMeatProducts","MntFishProducts","MntGoldProds"。另一個是byvar，給的是market中的Education。這個函數首先會找到byvar中有哪些類別的資料，所以會用到unique()去篩掉重複的類別，並將答案存在by。接著利用迴圈和subset()這個函數去找每個by中的類別在var中所有相同類別的數值的平均。最後將答案新增到mout這個data。而barplot的圖中有五種顏色的長條圖，分別是var中的五個變數。這張圖說明了var中的每個變數在各個不同的教育程度中的平均數值。
```
